### ISSUE TITLE
怎么修改kubernetes etcd数据呢

### ISSUE THREAD

**Issue by ygqygq2** [etcd-manage/etcd-manage-ui#2]
大佬，通过ui查看到kubernetes中etcd数据是乱码的，怎么修改呢？

**Comment by shiguanghuxian** [comment]
这个有计划支持k8s存储的值，只是暂时没时间去处理，最近加班多眼睛疼，最近不熬夜了😂

**Comment by ygqygq2** [comment]
@shiguanghuxian 期待中。上次我直接想修改ceph monitor的ip，结果kubectl get pv  不行了，pvc不能创建，吓死我了，后面我把修改的那个key都删除了才好，不敢乱动了。
