### ISSUE TITLE
无法添加etcd节点

### ISSUE THREAD

**Issue by ne1000** [etcd-manage/etcd-manage-ui#6]
无法添加etcd，etcd_servers表里也没这个字段
```
{"msg":"Error 1054: Unknown column 'created_at' in 'field list'"}
```

**Comment by shiguanghuxian** [comment]
请使用最新的sql结构，有问题可以联系我
[https://github.com/etcd-manage/etcd-manage-server/blob/master/data/etcd-manage19-08-26.sql](https://github.com/etcd-manage/etcd-manage-server/blob/master/data/etcd-manage19-08-26.sql)

**Comment by ne1000** [comment]
@shiguanghuxian 已解决，谢谢
